/*
 * Copyright (C) 2013 Andrew Comminos
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.celt7;

public class CELT7 implements CELT7Constants {
  public static SWIGTYPE_p_CELTMode celt_mode_create(int Fs, int frame_size, int[] error) {
    long cPtr = CELT7JNI.celt_mode_create(Fs, frame_size, error);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CELTMode(cPtr, false);
  }

  public static void celt_mode_destroy(SWIGTYPE_p_CELTMode mode) {
    CELT7JNI.celt_mode_destroy(SWIGTYPE_p_CELTMode.getCPtr(mode));
  }

  public static int celt_mode_info(SWIGTYPE_p_CELTMode mode, int request, int[] value) {
    return CELT7JNI.celt_mode_info(SWIGTYPE_p_CELTMode.getCPtr(mode), request, value);
  }

  public static SWIGTYPE_p_CELTEncoder celt_encoder_create(SWIGTYPE_p_CELTMode mode, int channels, int[] error) {
    long cPtr = CELT7JNI.celt_encoder_create(SWIGTYPE_p_CELTMode.getCPtr(mode), channels, error);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CELTEncoder(cPtr, false);
  }

  public static void celt_encoder_destroy(SWIGTYPE_p_CELTEncoder st) {
    CELT7JNI.celt_encoder_destroy(SWIGTYPE_p_CELTEncoder.getCPtr(st));
  }

  public static int celt_encode_float(SWIGTYPE_p_CELTEncoder st, float[] pcm, float[] optional_synthesis, byte[] compressed, int nbCompressedBytes) {
    return CELT7JNI.celt_encode_float(SWIGTYPE_p_CELTEncoder.getCPtr(st), pcm, optional_synthesis, compressed, nbCompressedBytes);
  }

  public static int celt_encode(SWIGTYPE_p_CELTEncoder st, short[] pcm, short[] optional_synthesis, byte[] compressed, int nbCompressedBytes) {
    return CELT7JNI.celt_encode(SWIGTYPE_p_CELTEncoder.getCPtr(st), pcm, optional_synthesis, compressed, nbCompressedBytes);
  }

  public static int celt_encoder_ctl(SWIGTYPE_p_CELTEncoder st, int request, int[] value) {
    return CELT7JNI.celt_encoder_ctl(SWIGTYPE_p_CELTEncoder.getCPtr(st), request, value);
  }

  public static SWIGTYPE_p_CELTDecoder celt_decoder_create(SWIGTYPE_p_CELTMode mode, int channels, int[] error) {
    long cPtr = CELT7JNI.celt_decoder_create(SWIGTYPE_p_CELTMode.getCPtr(mode), channels, error);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CELTDecoder(cPtr, false);
  }

  public static void celt_decoder_destroy(SWIGTYPE_p_CELTDecoder st) {
    CELT7JNI.celt_decoder_destroy(SWIGTYPE_p_CELTDecoder.getCPtr(st));
  }

  public static int celt_decode_float(SWIGTYPE_p_CELTDecoder st, byte[] data, int len, float[] pcm) {
    return CELT7JNI.celt_decode_float(SWIGTYPE_p_CELTDecoder.getCPtr(st), data, len, pcm);
  }

  public static int celt_decode(SWIGTYPE_p_CELTDecoder st, byte[] data, int len, short[] pcm) {
    return CELT7JNI.celt_decode(SWIGTYPE_p_CELTDecoder.getCPtr(st), data, len, pcm);
  }

  public static int celt_decoder_ctl(SWIGTYPE_p_CELTDecoder st, int request) {
    return CELT7JNI.celt_decoder_ctl(SWIGTYPE_p_CELTDecoder.getCPtr(st), request);
  }

  public static byte[] celt_strerror(int error) {
    return CELT7JNI.celt_strerror(error);
  }

}
