/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.celt7;

public interface CELT7Constants {
  public final static int CELT_OK = CELT7JNI.CELT_OK_get();
  public final static int CELT_BAD_ARG = CELT7JNI.CELT_BAD_ARG_get();
  public final static int CELT_INVALID_MODE = CELT7JNI.CELT_INVALID_MODE_get();
  public final static int CELT_INTERNAL_ERROR = CELT7JNI.CELT_INTERNAL_ERROR_get();
  public final static int CELT_CORRUPTED_DATA = CELT7JNI.CELT_CORRUPTED_DATA_get();
  public final static int CELT_UNIMPLEMENTED = CELT7JNI.CELT_UNIMPLEMENTED_get();
  public final static int CELT_INVALID_STATE = CELT7JNI.CELT_INVALID_STATE_get();
  public final static int CELT_ALLOC_FAIL = CELT7JNI.CELT_ALLOC_FAIL_get();
  public final static int CELT_GET_MODE_REQUEST = CELT7JNI.CELT_GET_MODE_REQUEST_get();
  public final static int CELT_SET_COMPLEXITY_REQUEST = CELT7JNI.CELT_SET_COMPLEXITY_REQUEST_get();
  public final static int CELT_SET_PREDICTION_REQUEST = CELT7JNI.CELT_SET_PREDICTION_REQUEST_get();
  public final static int CELT_SET_VBR_RATE_REQUEST = CELT7JNI.CELT_SET_VBR_RATE_REQUEST_get();
  public final static int CELT_RESET_STATE_REQUEST = CELT7JNI.CELT_RESET_STATE_REQUEST_get();
  public final static int CELT_RESET_STATE = CELT7JNI.CELT_RESET_STATE_get();
  public final static int CELT_GET_FRAME_SIZE = CELT7JNI.CELT_GET_FRAME_SIZE_get();
  public final static int CELT_GET_LOOKAHEAD = CELT7JNI.CELT_GET_LOOKAHEAD_get();
  public final static int CELT_GET_SAMPLE_RATE = CELT7JNI.CELT_GET_SAMPLE_RATE_get();
  public final static int CELT_GET_BITSTREAM_VERSION = CELT7JNI.CELT_GET_BITSTREAM_VERSION_get();
}
