/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.speex;

public class JitterBufferPacket {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JitterBufferPacket(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JitterBufferPacket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpeexJNI.delete_JitterBufferPacket(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(byte[] value) {
    SpeexJNI.JitterBufferPacket_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
    return SpeexJNI.JitterBufferPacket_data_get(swigCPtr, this);
  }

  public void setLen(long value) {
    SpeexJNI.JitterBufferPacket_len_set(swigCPtr, this, value);
  }

  public long getLen() {
    return SpeexJNI.JitterBufferPacket_len_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SpeexJNI.JitterBufferPacket_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SpeexJNI.JitterBufferPacket_timestamp_get(swigCPtr, this);
  }

  public void setSpan(long value) {
    SpeexJNI.JitterBufferPacket_span_set(swigCPtr, this, value);
  }

  public long getSpan() {
    return SpeexJNI.JitterBufferPacket_span_get(swigCPtr, this);
  }

  public void setSequence(int value) {
    SpeexJNI.JitterBufferPacket_sequence_set(swigCPtr, this, value);
  }

  public int getSequence() {
    return SpeexJNI.JitterBufferPacket_sequence_get(swigCPtr, this);
  }

  public void setUser_data(long value) {
    SpeexJNI.JitterBufferPacket_user_data_set(swigCPtr, this, value);
  }

  public long getUser_data() {
    return SpeexJNI.JitterBufferPacket_user_data_get(swigCPtr, this);
  }

  public JitterBufferPacket() {
    this(SpeexJNI.new_JitterBufferPacket(), true);
  }

}
