/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.speex;

public interface SpeexConstants {
  public final static int JITTER_BUFFER_OK = SpeexJNI.JITTER_BUFFER_OK_get();
  public final static int JITTER_BUFFER_MISSING = SpeexJNI.JITTER_BUFFER_MISSING_get();
  public final static int JITTER_BUFFER_INSERTION = SpeexJNI.JITTER_BUFFER_INSERTION_get();
  public final static int JITTER_BUFFER_INTERNAL_ERROR = SpeexJNI.JITTER_BUFFER_INTERNAL_ERROR_get();
  public final static int JITTER_BUFFER_BAD_ARGUMENT = SpeexJNI.JITTER_BUFFER_BAD_ARGUMENT_get();
  public final static int JITTER_BUFFER_SET_MARGIN = SpeexJNI.JITTER_BUFFER_SET_MARGIN_get();
  public final static int JITTER_BUFFER_GET_MARGIN = SpeexJNI.JITTER_BUFFER_GET_MARGIN_get();
  public final static int JITTER_BUFFER_GET_AVAILABLE_COUNT = SpeexJNI.JITTER_BUFFER_GET_AVAILABLE_COUNT_get();
  public final static int JITTER_BUFFER_GET_AVALIABLE_COUNT = SpeexJNI.JITTER_BUFFER_GET_AVALIABLE_COUNT_get();
  public final static int JITTER_BUFFER_SET_DESTROY_CALLBACK = SpeexJNI.JITTER_BUFFER_SET_DESTROY_CALLBACK_get();
  public final static int JITTER_BUFFER_GET_DESTROY_CALLBACK = SpeexJNI.JITTER_BUFFER_GET_DESTROY_CALLBACK_get();
  public final static int JITTER_BUFFER_SET_DELAY_STEP = SpeexJNI.JITTER_BUFFER_SET_DELAY_STEP_get();
  public final static int JITTER_BUFFER_GET_DELAY_STEP = SpeexJNI.JITTER_BUFFER_GET_DELAY_STEP_get();
  public final static int JITTER_BUFFER_SET_CONCEALMENT_SIZE = SpeexJNI.JITTER_BUFFER_SET_CONCEALMENT_SIZE_get();
  public final static int JITTER_BUFFER_GET_CONCEALMENT_SIZE = SpeexJNI.JITTER_BUFFER_GET_CONCEALMENT_SIZE_get();
  public final static int JITTER_BUFFER_SET_MAX_LATE_RATE = SpeexJNI.JITTER_BUFFER_SET_MAX_LATE_RATE_get();
  public final static int JITTER_BUFFER_GET_MAX_LATE_RATE = SpeexJNI.JITTER_BUFFER_GET_MAX_LATE_RATE_get();
  public final static int JITTER_BUFFER_SET_LATE_COST = SpeexJNI.JITTER_BUFFER_SET_LATE_COST_get();
  public final static int JITTER_BUFFER_GET_LATE_COST = SpeexJNI.JITTER_BUFFER_GET_LATE_COST_get();
  public final static int SPEEX_ECHO_GET_FRAME_SIZE = SpeexJNI.SPEEX_ECHO_GET_FRAME_SIZE_get();
  public final static int SPEEX_ECHO_SET_SAMPLING_RATE = SpeexJNI.SPEEX_ECHO_SET_SAMPLING_RATE_get();
  public final static int SPEEX_ECHO_GET_SAMPLING_RATE = SpeexJNI.SPEEX_ECHO_GET_SAMPLING_RATE_get();
  public final static int SPEEX_ECHO_GET_IMPULSE_RESPONSE_SIZE = SpeexJNI.SPEEX_ECHO_GET_IMPULSE_RESPONSE_SIZE_get();
  public final static int SPEEX_ECHO_GET_IMPULSE_RESPONSE = SpeexJNI.SPEEX_ECHO_GET_IMPULSE_RESPONSE_get();
  public final static int SPEEX_RESAMPLER_QUALITY_MAX = SpeexJNI.SPEEX_RESAMPLER_QUALITY_MAX_get();
  public final static int SPEEX_RESAMPLER_QUALITY_MIN = SpeexJNI.SPEEX_RESAMPLER_QUALITY_MIN_get();
  public final static int SPEEX_RESAMPLER_QUALITY_DEFAULT = SpeexJNI.SPEEX_RESAMPLER_QUALITY_DEFAULT_get();
  public final static int SPEEX_RESAMPLER_QUALITY_VOIP = SpeexJNI.SPEEX_RESAMPLER_QUALITY_VOIP_get();
  public final static int SPEEX_RESAMPLER_QUALITY_DESKTOP = SpeexJNI.SPEEX_RESAMPLER_QUALITY_DESKTOP_get();
  public final static int RESAMPLER_ERR_SUCCESS = SpeexJNI.RESAMPLER_ERR_SUCCESS_get();
  public final static int RESAMPLER_ERR_ALLOC_FAILED = SpeexJNI.RESAMPLER_ERR_ALLOC_FAILED_get();
  public final static int RESAMPLER_ERR_BAD_STATE = SpeexJNI.RESAMPLER_ERR_BAD_STATE_get();
  public final static int RESAMPLER_ERR_INVALID_ARG = SpeexJNI.RESAMPLER_ERR_INVALID_ARG_get();
  public final static int RESAMPLER_ERR_PTR_OVERLAP = SpeexJNI.RESAMPLER_ERR_PTR_OVERLAP_get();
  public final static int RESAMPLER_ERR_MAX_ERROR = SpeexJNI.RESAMPLER_ERR_MAX_ERROR_get();

}
