/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.celt7;

public class CELT7Decoder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CELT7Decoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CELT7Decoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CELT7JNI.delete_CELT7Decoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CELT7Decoder() {
    this(CELT7JNI.new_CELT7Decoder(), true);
  }

}
