/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.celt11;

public class CELT11 implements CELT11Constants {
  public static CELT11Mode celt_mode_create(int Fs, int frame_size, int[] error) {
    long cPtr = CELT11JNI.celt_mode_create(Fs, frame_size, error);
    return (cPtr == 0) ? null : new CELT11Mode(cPtr, false);
  }

  public static void celt_mode_destroy(CELT11Mode mode) {
    CELT11JNI.celt_mode_destroy(CELT11Mode.getCPtr(mode), mode);
  }

  public static int celt_mode_info(CELT11Mode mode, int request, int[] value) {
    return CELT11JNI.celt_mode_info(CELT11Mode.getCPtr(mode), mode, request, value);
  }

  public static int celt_encoder_get_size(int channels) {
    return CELT11JNI.celt_encoder_get_size(channels);
  }

  public static int celt_encoder_get_size_custom(CELT11Mode mode, int channels) {
    return CELT11JNI.celt_encoder_get_size_custom(CELT11Mode.getCPtr(mode), mode, channels);
  }

  public static CELT11Encoder celt_encoder_create(int sampling_rate, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_encoder_create(sampling_rate, channels, error);
    return (cPtr == 0) ? null : new CELT11Encoder(cPtr, false);
  }

  public static CELT11Encoder celt_encoder_create_custom(CELT11Mode mode, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_encoder_create_custom(CELT11Mode.getCPtr(mode), mode, channels, error);
    return (cPtr == 0) ? null : new CELT11Encoder(cPtr, false);
  }

  public static CELT11Encoder celt_encoder_init(CELT11Encoder st, int sampling_rate, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_encoder_init(CELT11Encoder.getCPtr(st), st, sampling_rate, channels, error);
    return (cPtr == 0) ? null : new CELT11Encoder(cPtr, false);
  }

  public static CELT11Encoder celt_encoder_init_custom(CELT11Encoder st, CELT11Mode mode, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_encoder_init_custom(CELT11Encoder.getCPtr(st), st, CELT11Mode.getCPtr(mode), mode, channels, error);
    return (cPtr == 0) ? null : new CELT11Encoder(cPtr, false);
  }

  public static void celt_encoder_destroy(CELT11Encoder st) {
    CELT11JNI.celt_encoder_destroy(CELT11Encoder.getCPtr(st), st);
  }

  public static int celt_encode_float(CELT11Encoder st, float[] pcm, int frame_size, byte[] compressed, int maxCompressedBytes) {
    return CELT11JNI.celt_encode_float(CELT11Encoder.getCPtr(st), st, pcm, frame_size, compressed, maxCompressedBytes);
  }

  public static int celt_encode(CELT11Encoder st, short[] pcm, int frame_size, byte[] compressed, int maxCompressedBytes) {
    return CELT11JNI.celt_encode(CELT11Encoder.getCPtr(st), st, pcm, frame_size, compressed, maxCompressedBytes);
  }

  public static int celt_encoder_ctl(CELT11Encoder st, int request, int[] value) {
    return CELT11JNI.celt_encoder_ctl(CELT11Encoder.getCPtr(st), st, request, value);
  }

  public static int celt_decoder_get_size(int channels) {
    return CELT11JNI.celt_decoder_get_size(channels);
  }

  public static int celt_decoder_get_size_custom(CELT11Mode mode, int channels) {
    return CELT11JNI.celt_decoder_get_size_custom(CELT11Mode.getCPtr(mode), mode, channels);
  }

  public static CELT11Decoder celt_decoder_create(int sampling_rate, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_decoder_create(sampling_rate, channels, error);
    return (cPtr == 0) ? null : new CELT11Decoder(cPtr, false);
  }

  public static CELT11Decoder celt_decoder_create_custom(CELT11Mode mode, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_decoder_create_custom(CELT11Mode.getCPtr(mode), mode, channels, error);
    return (cPtr == 0) ? null : new CELT11Decoder(cPtr, false);
  }

  public static CELT11Decoder celt_decoder_init(CELT11Decoder st, int sampling_rate, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_decoder_init(CELT11Decoder.getCPtr(st), st, sampling_rate, channels, error);
    return (cPtr == 0) ? null : new CELT11Decoder(cPtr, false);
  }

  public static CELT11Decoder celt_decoder_init_custom(CELT11Decoder st, CELT11Mode mode, int channels, int[] error) {
    long cPtr = CELT11JNI.celt_decoder_init_custom(CELT11Decoder.getCPtr(st), st, CELT11Mode.getCPtr(mode), mode, channels, error);
    return (cPtr == 0) ? null : new CELT11Decoder(cPtr, false);
  }

  public static void celt_decoder_destroy(CELT11Decoder st) {
    CELT11JNI.celt_decoder_destroy(CELT11Decoder.getCPtr(st), st);
  }

  public static int celt_decode_float(CELT11Decoder st, byte[] data, int len, float[] pcm, int frame_size) {
    return CELT11JNI.celt_decode_float(CELT11Decoder.getCPtr(st), st, data, len, pcm, frame_size);
  }

  public static int celt_decode(CELT11Decoder st, byte[] data, int len, short[] pcm, int frame_size) {
    return CELT11JNI.celt_decode(CELT11Decoder.getCPtr(st), st, data, len, pcm, frame_size);
  }

  public static int celt_decoder_ctl(CELT11Decoder st, int request) {
    return CELT11JNI.celt_decoder_ctl(CELT11Decoder.getCPtr(st), st, request);
  }

  public static byte[] celt_strerror(int error) {
    return CELT11JNI.celt_strerror(error);
  }

}
