/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.speex;

public class SpeexBits {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SpeexBits(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpeexBits obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpeexJNI.delete_SpeexBits(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChars(byte[] value) {
    SpeexJNI.SpeexBits_chars_set(swigCPtr, this, value);
  }

  public byte[] getChars() {
    return SpeexJNI.SpeexBits_chars_get(swigCPtr, this);
  }

  public void setNbBits(int value) {
    SpeexJNI.SpeexBits_nbBits_set(swigCPtr, this, value);
  }

  public int getNbBits() {
    return SpeexJNI.SpeexBits_nbBits_get(swigCPtr, this);
  }

  public void setCharPtr(int value) {
    SpeexJNI.SpeexBits_charPtr_set(swigCPtr, this, value);
  }

  public int getCharPtr() {
    return SpeexJNI.SpeexBits_charPtr_get(swigCPtr, this);
  }

  public void setBitPtr(int value) {
    SpeexJNI.SpeexBits_bitPtr_set(swigCPtr, this, value);
  }

  public int getBitPtr() {
    return SpeexJNI.SpeexBits_bitPtr_get(swigCPtr, this);
  }

  public void setOwner(int value) {
    SpeexJNI.SpeexBits_owner_set(swigCPtr, this, value);
  }

  public int getOwner() {
    return SpeexJNI.SpeexBits_owner_get(swigCPtr, this);
  }

  public void setOverflow(int value) {
    SpeexJNI.SpeexBits_overflow_set(swigCPtr, this, value);
  }

  public int getOverflow() {
    return SpeexJNI.SpeexBits_overflow_get(swigCPtr, this);
  }

  public void setBuf_size(int value) {
    SpeexJNI.SpeexBits_buf_size_set(swigCPtr, this, value);
  }

  public int getBuf_size() {
    return SpeexJNI.SpeexBits_buf_size_get(swigCPtr, this);
  }

  public void setReserved1(int value) {
    SpeexJNI.SpeexBits_reserved1_set(swigCPtr, this, value);
  }

  public int getReserved1() {
    return SpeexJNI.SpeexBits_reserved1_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_void value) {
    SpeexJNI.SpeexBits_reserved2_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved2() {
    long cPtr = SpeexJNI.SpeexBits_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SpeexBits() {
    this(SpeexJNI.new_SpeexBits(), true);
  }

}
