/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.opus;

public interface OpusConstants {
  public final static int OPUS_OK = OpusJNI.OPUS_OK_get();
  public final static int OPUS_BAD_ARG = OpusJNI.OPUS_BAD_ARG_get();
  public final static int OPUS_BUFFER_TOO_SMALL = OpusJNI.OPUS_BUFFER_TOO_SMALL_get();
  public final static int OPUS_INTERNAL_ERROR = OpusJNI.OPUS_INTERNAL_ERROR_get();
  public final static int OPUS_INVALID_PACKET = OpusJNI.OPUS_INVALID_PACKET_get();
  public final static int OPUS_UNIMPLEMENTED = OpusJNI.OPUS_UNIMPLEMENTED_get();
  public final static int OPUS_INVALID_STATE = OpusJNI.OPUS_INVALID_STATE_get();
  public final static int OPUS_ALLOC_FAIL = OpusJNI.OPUS_ALLOC_FAIL_get();
  public final static int OPUS_SET_APPLICATION_REQUEST = OpusJNI.OPUS_SET_APPLICATION_REQUEST_get();
  public final static int OPUS_GET_APPLICATION_REQUEST = OpusJNI.OPUS_GET_APPLICATION_REQUEST_get();
  public final static int OPUS_SET_BITRATE_REQUEST = OpusJNI.OPUS_SET_BITRATE_REQUEST_get();
  public final static int OPUS_GET_BITRATE_REQUEST = OpusJNI.OPUS_GET_BITRATE_REQUEST_get();
  public final static int OPUS_SET_MAX_BANDWIDTH_REQUEST = OpusJNI.OPUS_SET_MAX_BANDWIDTH_REQUEST_get();
  public final static int OPUS_GET_MAX_BANDWIDTH_REQUEST = OpusJNI.OPUS_GET_MAX_BANDWIDTH_REQUEST_get();
  public final static int OPUS_SET_VBR_REQUEST = OpusJNI.OPUS_SET_VBR_REQUEST_get();
  public final static int OPUS_GET_VBR_REQUEST = OpusJNI.OPUS_GET_VBR_REQUEST_get();
  public final static int OPUS_SET_BANDWIDTH_REQUEST = OpusJNI.OPUS_SET_BANDWIDTH_REQUEST_get();
  public final static int OPUS_GET_BANDWIDTH_REQUEST = OpusJNI.OPUS_GET_BANDWIDTH_REQUEST_get();
  public final static int OPUS_SET_COMPLEXITY_REQUEST = OpusJNI.OPUS_SET_COMPLEXITY_REQUEST_get();
  public final static int OPUS_GET_COMPLEXITY_REQUEST = OpusJNI.OPUS_GET_COMPLEXITY_REQUEST_get();
  public final static int OPUS_SET_INBAND_FEC_REQUEST = OpusJNI.OPUS_SET_INBAND_FEC_REQUEST_get();
  public final static int OPUS_GET_INBAND_FEC_REQUEST = OpusJNI.OPUS_GET_INBAND_FEC_REQUEST_get();
  public final static int OPUS_SET_PACKET_LOSS_PERC_REQUEST = OpusJNI.OPUS_SET_PACKET_LOSS_PERC_REQUEST_get();
  public final static int OPUS_GET_PACKET_LOSS_PERC_REQUEST = OpusJNI.OPUS_GET_PACKET_LOSS_PERC_REQUEST_get();
  public final static int OPUS_SET_DTX_REQUEST = OpusJNI.OPUS_SET_DTX_REQUEST_get();
  public final static int OPUS_GET_DTX_REQUEST = OpusJNI.OPUS_GET_DTX_REQUEST_get();
  public final static int OPUS_SET_VBR_CONSTRAINT_REQUEST = OpusJNI.OPUS_SET_VBR_CONSTRAINT_REQUEST_get();
  public final static int OPUS_GET_VBR_CONSTRAINT_REQUEST = OpusJNI.OPUS_GET_VBR_CONSTRAINT_REQUEST_get();
  public final static int OPUS_SET_FORCE_CHANNELS_REQUEST = OpusJNI.OPUS_SET_FORCE_CHANNELS_REQUEST_get();
  public final static int OPUS_GET_FORCE_CHANNELS_REQUEST = OpusJNI.OPUS_GET_FORCE_CHANNELS_REQUEST_get();
  public final static int OPUS_SET_SIGNAL_REQUEST = OpusJNI.OPUS_SET_SIGNAL_REQUEST_get();
  public final static int OPUS_GET_SIGNAL_REQUEST = OpusJNI.OPUS_GET_SIGNAL_REQUEST_get();
  public final static int OPUS_GET_LOOKAHEAD_REQUEST = OpusJNI.OPUS_GET_LOOKAHEAD_REQUEST_get();
  public final static int OPUS_GET_SAMPLE_RATE_REQUEST = OpusJNI.OPUS_GET_SAMPLE_RATE_REQUEST_get();
  public final static int OPUS_GET_FINAL_RANGE_REQUEST = OpusJNI.OPUS_GET_FINAL_RANGE_REQUEST_get();
  public final static int OPUS_GET_PITCH_REQUEST = OpusJNI.OPUS_GET_PITCH_REQUEST_get();
  public final static int OPUS_SET_GAIN_REQUEST = OpusJNI.OPUS_SET_GAIN_REQUEST_get();
  public final static int OPUS_GET_GAIN_REQUEST = OpusJNI.OPUS_GET_GAIN_REQUEST_get();
  public final static int OPUS_SET_LSB_DEPTH_REQUEST = OpusJNI.OPUS_SET_LSB_DEPTH_REQUEST_get();
  public final static int OPUS_GET_LSB_DEPTH_REQUEST = OpusJNI.OPUS_GET_LSB_DEPTH_REQUEST_get();
  public final static int OPUS_GET_LAST_PACKET_DURATION_REQUEST = OpusJNI.OPUS_GET_LAST_PACKET_DURATION_REQUEST_get();
  public final static int OPUS_SET_EXPERT_FRAME_DURATION_REQUEST = OpusJNI.OPUS_SET_EXPERT_FRAME_DURATION_REQUEST_get();
  public final static int OPUS_GET_EXPERT_FRAME_DURATION_REQUEST = OpusJNI.OPUS_GET_EXPERT_FRAME_DURATION_REQUEST_get();
  public final static int OPUS_AUTO = OpusJNI.OPUS_AUTO_get();
  public final static int OPUS_BITRATE_MAX = OpusJNI.OPUS_BITRATE_MAX_get();
  public final static int OPUS_APPLICATION_VOIP = OpusJNI.OPUS_APPLICATION_VOIP_get();
  public final static int OPUS_APPLICATION_AUDIO = OpusJNI.OPUS_APPLICATION_AUDIO_get();
  public final static int OPUS_APPLICATION_RESTRICTED_LOWDELAY = OpusJNI.OPUS_APPLICATION_RESTRICTED_LOWDELAY_get();
  public final static int OPUS_SIGNAL_VOICE = OpusJNI.OPUS_SIGNAL_VOICE_get();
  public final static int OPUS_SIGNAL_MUSIC = OpusJNI.OPUS_SIGNAL_MUSIC_get();
  public final static int OPUS_BANDWIDTH_NARROWBAND = OpusJNI.OPUS_BANDWIDTH_NARROWBAND_get();
  public final static int OPUS_BANDWIDTH_MEDIUMBAND = OpusJNI.OPUS_BANDWIDTH_MEDIUMBAND_get();
  public final static int OPUS_BANDWIDTH_WIDEBAND = OpusJNI.OPUS_BANDWIDTH_WIDEBAND_get();
  public final static int OPUS_BANDWIDTH_SUPERWIDEBAND = OpusJNI.OPUS_BANDWIDTH_SUPERWIDEBAND_get();
  public final static int OPUS_BANDWIDTH_FULLBAND = OpusJNI.OPUS_BANDWIDTH_FULLBAND_get();
  public final static int OPUS_FRAMESIZE_ARG = OpusJNI.OPUS_FRAMESIZE_ARG_get();
  public final static int OPUS_FRAMESIZE_2_5_MS = OpusJNI.OPUS_FRAMESIZE_2_5_MS_get();
  public final static int OPUS_FRAMESIZE_5_MS = OpusJNI.OPUS_FRAMESIZE_5_MS_get();
  public final static int OPUS_FRAMESIZE_10_MS = OpusJNI.OPUS_FRAMESIZE_10_MS_get();
  public final static int OPUS_FRAMESIZE_20_MS = OpusJNI.OPUS_FRAMESIZE_20_MS_get();
  public final static int OPUS_FRAMESIZE_40_MS = OpusJNI.OPUS_FRAMESIZE_40_MS_get();
  public final static int OPUS_FRAMESIZE_60_MS = OpusJNI.OPUS_FRAMESIZE_60_MS_get();
  public final static int OPUS_FRAMESIZE_VARIABLE = OpusJNI.OPUS_FRAMESIZE_VARIABLE_get();
  public final static int OPUS_RESET_STATE = OpusJNI.OPUS_RESET_STATE_get();
}
