/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <opus_defines.h>
#include <opus_types.h>
#include <opus.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BAD_1ARG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BUFFER_1TOO_1SMALL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1INTERNAL_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1INVALID_1PACKET_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1UNIMPLEMENTED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1INVALID_1STATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1ALLOC_1FAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1APPLICATION_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4000);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1APPLICATION_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4001);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1BITRATE_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4002);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1BITRATE_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4003);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1MAX_1BANDWIDTH_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4004);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1MAX_1BANDWIDTH_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4005);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1VBR_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4006);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1VBR_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4007);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1BANDWIDTH_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4008);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1BANDWIDTH_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4009);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1COMPLEXITY_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4010);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1COMPLEXITY_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4011);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1INBAND_1FEC_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4012);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1INBAND_1FEC_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4013);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1PACKET_1LOSS_1PERC_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4014);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1PACKET_1LOSS_1PERC_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4015);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1DTX_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4016);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1DTX_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4017);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1VBR_1CONSTRAINT_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4020);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1VBR_1CONSTRAINT_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4021);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1FORCE_1CHANNELS_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4022);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1FORCE_1CHANNELS_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4023);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1SIGNAL_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4024);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1SIGNAL_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4025);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1LOOKAHEAD_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4027);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1SAMPLE_1RATE_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4029);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1FINAL_1RANGE_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4031);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1PITCH_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4033);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1GAIN_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4034);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1GAIN_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4045);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SET_1LSB_1DEPTH_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4036);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1LSB_1DEPTH_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4037);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1GET_1LAST_1PACKET_1DURATION_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4039);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1AUTO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-1000);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BITRATE_1MAX_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1APPLICATION_1VOIP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2048);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1APPLICATION_1AUDIO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2049);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1APPLICATION_1RESTRICTED_1LOWDELAY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2051);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SIGNAL_1VOICE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3001);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1SIGNAL_1MUSIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3002);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BANDWIDTH_1NARROWBAND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1101);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BANDWIDTH_1MEDIUMBAND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1102);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BANDWIDTH_1WIDEBAND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1103);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BANDWIDTH_1SUPERWIDEBAND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1104);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1BANDWIDTH_1FULLBAND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1105);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_OPUS_1RESET_1STATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4028);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jbyteArray JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1strerror(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jbyteArray jresult = 0 ;
  int arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (char *)opus_strerror(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jbyteArray JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1get_1version_1string(JNIEnv *jenv, jclass jcls) {
  jbyteArray jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)opus_get_version_string();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1encoder_1get_1size(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)opus_encoder_get_size(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1encoder_1create(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jintArray jarg4) {
  jlong jresult = 0 ;
  opus_int32 arg1 ;
  int arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  OpusEncoder *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (opus_int32)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (int *) (*jenv)->GetIntArrayElements(jenv, jarg4, 0); 
  }
  result = (OpusEncoder *)opus_encoder_create(arg1,arg2,arg3,arg4);
  *(OpusEncoder **)&jresult = result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg4, (jint *)arg4, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1encoder_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  OpusEncoder *arg1 = (OpusEncoder *) 0 ;
  opus_int32 arg2 ;
  int arg3 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusEncoder **)&jarg1; 
  arg2 = (opus_int32)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (int)opus_encoder_init(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1encode(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2, jint jarg3, jbyteArray jarg4, jint jarg5) {
  jint jresult = 0 ;
  OpusEncoder *arg1 = (OpusEncoder *) 0 ;
  opus_int16 *arg2 = (opus_int16 *) 0 ;
  int arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  opus_int32 arg5 ;
  opus_int32 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusEncoder **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = (opus_int16 *) (*jenv)->GetShortArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (int)jarg3; 
  {
    arg4 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg4, 0); 
  }
  arg5 = (opus_int32)jarg5; 
  result = (opus_int32)opus_encode(arg1,(short const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg2, (jshort *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg4, (jbyte *) arg4, 0); 
  }
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1encode_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloatArray jarg2, jint jarg3, jbyteArray jarg4, jint jarg5) {
  jint jresult = 0 ;
  OpusEncoder *arg1 = (OpusEncoder *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  opus_int32 arg5 ;
  opus_int32 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusEncoder **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = (float *) (*jenv)->GetFloatArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (int)jarg3; 
  {
    arg4 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg4, 0); 
  }
  arg5 = (opus_int32)jarg5; 
  result = (opus_int32)opus_encode_float(arg1,(float const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseFloatArrayElements(jenv, jarg2, (jfloat *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg4, (jbyte *) arg4, 0); 
  }
  
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1encoder_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OpusEncoder *arg1 = (OpusEncoder *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusEncoder **)&jarg1; 
  opus_encoder_destroy(arg1);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1encoder_1ctl(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jintArray jarg3) {
  jint jresult = 0 ;
  OpusEncoder *arg1 = (OpusEncoder *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusEncoder **)&jarg1; 
  arg2 = (int)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (int *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  result = (int)opus_encoder_ctl(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decoder_1get_1size(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)opus_decoder_get_size(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decoder_1create(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jintArray jarg3) {
  jlong jresult = 0 ;
  opus_int32 arg1 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  OpusDecoder *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (opus_int32)jarg1; 
  arg2 = (int)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (int *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  result = (OpusDecoder *)opus_decoder_create(arg1,arg2,arg3);
  *(OpusDecoder **)&jresult = result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decoder_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  OpusDecoder *arg1 = (OpusDecoder *) 0 ;
  opus_int32 arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusDecoder **)&jarg1; 
  arg2 = (opus_int32)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)opus_decoder_init(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decode(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2, jint jarg3, jshortArray jarg4, jint jarg5, jint jarg6) {
  jint jresult = 0 ;
  OpusDecoder *arg1 = (OpusDecoder *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  opus_int32 arg3 ;
  opus_int16 *arg4 = (opus_int16 *) 0 ;
  int arg5 ;
  int arg6 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusDecoder **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (opus_int32)jarg3; 
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (opus_int16 *) (*jenv)->GetShortArrayElements(jenv, jarg4, 0); 
  }
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  result = (int)opus_decode(arg1,(unsigned char const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg4, (jshort *)arg4, 0); 
  }
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decode_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2, jint jarg3, jfloatArray jarg4, jint jarg5, jint jarg6) {
  jint jresult = 0 ;
  OpusDecoder *arg1 = (OpusDecoder *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  opus_int32 arg3 ;
  float *arg4 = (float *) 0 ;
  int arg5 ;
  int arg6 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusDecoder **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (opus_int32)jarg3; 
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (float *) (*jenv)->GetFloatArrayElements(jenv, jarg4, 0); 
  }
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  result = (int)opus_decode_float(arg1,(unsigned char const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  {
    (*jenv)->ReleaseFloatArrayElements(jenv, jarg4, (jfloat *)arg4, 0); 
  }
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decoder_1ctl(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  OpusDecoder *arg1 = (OpusDecoder *) 0 ;
  int arg2 ;
  void *arg3 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)opus_decoder_ctl(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decoder_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OpusDecoder *arg1 = (OpusDecoder *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusDecoder **)&jarg1; 
  opus_decoder_destroy(arg1);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1packet_1parse(JNIEnv *jenv, jclass jcls, jbyteArray jarg1, jint jarg2, jbyteArray jarg3, jlong jarg4, jlong jarg5, jintArray jarg6) {
  jint jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  opus_int32 arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char **arg4 ;
  short *arg5 ;
  int *arg6 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  arg2 = (opus_int32)jarg2; 
  {
    arg3 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg3, 0); 
  }
  arg4 = *(unsigned char ***)&jarg4; 
  arg5 = *(short **)&jarg5; 
  {
    if (!jarg6) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg6) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg6 = (int *) (*jenv)->GetIntArrayElements(jenv, jarg6, 0); 
  }
  result = (int)opus_packet_parse((unsigned char const *)arg1,arg2,arg3,(unsigned char const *(*))arg4,arg5,arg6);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg3, (jbyte *) arg3, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg6, (jint *)arg6, 0); 
  }
  
  
  
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1packet_1get_1bandwidth(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
  jint jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  result = (int)opus_packet_get_bandwidth((unsigned char const *)arg1);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1packet_1get_1samples_1per_1frame(JNIEnv *jenv, jclass jcls, jbyteArray jarg1, jint jarg2) {
  jint jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  opus_int32 arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  arg2 = (opus_int32)jarg2; 
  result = (int)opus_packet_get_samples_per_frame((unsigned char const *)arg1,arg2);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1packet_1get_1nb_1channels(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
  jint jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  result = (int)opus_packet_get_nb_channels((unsigned char const *)arg1);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1packet_1get_1nb_1frames(JNIEnv *jenv, jclass jcls, jbyteArray jarg1, jint jarg2) {
  jint jresult = 0 ;
  unsigned char *arg1 ;
  opus_int32 arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  arg2 = (opus_int32)jarg2; 
  result = (int)opus_packet_get_nb_frames((unsigned char const (*))arg1,arg2);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1packet_1get_1nb_1samples(JNIEnv *jenv, jclass jcls, jbyteArray jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  unsigned char *arg1 ;
  opus_int32 arg2 ;
  opus_int32 arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  arg2 = (opus_int32)jarg2; 
  arg3 = (opus_int32)jarg3; 
  result = (int)opus_packet_get_nb_samples((unsigned char const (*))arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1decoder_1get_1nb_1samples(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2, jint jarg3) {
  jint jresult = 0 ;
  OpusDecoder *arg1 = (OpusDecoder *) 0 ;
  unsigned char *arg2 ;
  opus_int32 arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusDecoder **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (opus_int32)jarg3; 
  result = (int)opus_decoder_get_nb_samples((struct OpusDecoder const *)arg1,(unsigned char const (*))arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1get_1size(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)opus_repacketizer_get_size();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1init(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  OpusRepacketizer *arg1 = (OpusRepacketizer *) 0 ;
  OpusRepacketizer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusRepacketizer **)&jarg1; 
  result = (OpusRepacketizer *)opus_repacketizer_init(arg1);
  *(OpusRepacketizer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OpusRepacketizer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (OpusRepacketizer *)opus_repacketizer_create();
  *(OpusRepacketizer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OpusRepacketizer *arg1 = (OpusRepacketizer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusRepacketizer **)&jarg1; 
  opus_repacketizer_destroy(arg1);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1cat(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2, jint jarg3) {
  jint jresult = 0 ;
  OpusRepacketizer *arg1 = (OpusRepacketizer *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  opus_int32 arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusRepacketizer **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (opus_int32)jarg3; 
  result = (int)opus_repacketizer_cat(arg1,(unsigned char const *)arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1out_1range(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jbyteArray jarg4, jint jarg5) {
  jint jresult = 0 ;
  OpusRepacketizer *arg1 = (OpusRepacketizer *) 0 ;
  int arg2 ;
  int arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  opus_int32 arg5 ;
  opus_int32 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusRepacketizer **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  {
    arg4 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg4, 0); 
  }
  arg5 = (opus_int32)jarg5; 
  result = (opus_int32)opus_repacketizer_out_range(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg4, (jbyte *) arg4, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1get_1nb_1frames(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  OpusRepacketizer *arg1 = (OpusRepacketizer *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusRepacketizer **)&jarg1; 
  result = (int)opus_repacketizer_get_nb_frames(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_opus_OpusJNI_opus_1repacketizer_1out(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2, jint jarg3) {
  jint jresult = 0 ;
  OpusRepacketizer *arg1 = (OpusRepacketizer *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  opus_int32 arg3 ;
  opus_int32 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OpusRepacketizer **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (opus_int32)jarg3; 
  result = (opus_int32)opus_repacketizer_out(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
  return jresult;
}


#ifdef __cplusplus
}
#endif

