/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <speex/speex_types.h>
#include <speex/speex_jitter.h>
#include <speex/speex_echo.h>
#include <speex/speex_resampler.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  {
    free(arg1->data);
    if (arg2) {
      arg1->data = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->data, (const char *)arg2);
    } else {
      arg1->data = 0;
    }
  }
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
}


SWIGEXPORT jbyteArray JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jbyteArray jresult = 0 ;
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  result = (char *) ((arg1)->data);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1len_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  if (arg1) (arg1)->len = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1len_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  result = (spx_uint32_t) ((arg1)->len);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1timestamp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  if (arg1) (arg1)->timestamp = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1timestamp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  result = (spx_uint32_t) ((arg1)->timestamp);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1span_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  if (arg1) (arg1)->span = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1span_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  result = (spx_uint32_t) ((arg1)->span);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1sequence_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint16_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  arg2 = (spx_uint16_t)jarg2; 
  if (arg1) (arg1)->sequence = arg2;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1sequence_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint16_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  result = (spx_uint16_t) ((arg1)->sequence);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1user_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  if (arg1) (arg1)->user_data = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JitterBufferPacket_1user_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  spx_uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  result = (spx_uint32_t) ((arg1)->user_data);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_new_1JitterBufferPacket(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct _JitterBufferPacket *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct _JitterBufferPacket *)calloc(1, sizeof(struct _JitterBufferPacket));
  *(struct _JitterBufferPacket **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_delete_1JitterBufferPacket(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct _JitterBufferPacket *arg1 = (struct _JitterBufferPacket *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct _JitterBufferPacket **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1MISSING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1INSERTION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1INTERNAL_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1BAD_1ARGUMENT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1SET_1MARGIN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1MARGIN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1AVAILABLE_1COUNT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1AVALIABLE_1COUNT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1SET_1DESTROY_1CALLBACK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1DESTROY_1CALLBACK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1SET_1DELAY_1STEP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1DELAY_1STEP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1SET_1CONCEALMENT_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1CONCEALMENT_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1SET_1MAX_1LATE_1RATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(10);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1MAX_1LATE_1RATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(11);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1SET_1LATE_1COST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(12);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_JITTER_1BUFFER_1GET_1LATE_1COST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(13);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1init(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  JitterBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (JitterBuffer *)jitter_buffer_init(arg1);
  *(JitterBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1reset(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(JitterBuffer **)&jarg1; 
  jitter_buffer_reset(arg1);
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(JitterBuffer **)&jarg1; 
  jitter_buffer_destroy(arg1);
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1put(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  JitterBufferPacket *arg2 = (JitterBufferPacket *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(JitterBuffer **)&jarg1; 
  arg2 = *(JitterBufferPacket **)&jarg2; 
  jitter_buffer_put(arg1,(struct _JitterBufferPacket const *)arg2);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_, jint jarg3, jintArray jarg4) {
  jint jresult = 0 ;
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  JitterBufferPacket *arg2 = (JitterBufferPacket *) 0 ;
  spx_int32_t arg3 ;
  spx_int32_t *arg4 = (spx_int32_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(JitterBuffer **)&jarg1; 
  arg2 = *(JitterBufferPacket **)&jarg2; 
  arg3 = (spx_int32_t)jarg3; 
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (spx_int32_t *) (*jenv)->GetIntArrayElements(jenv, jarg4, 0); 
  }
  result = (int)jitter_buffer_get(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg4, (jint *)arg4, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1get_1another(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  JitterBufferPacket *arg2 = (JitterBufferPacket *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(JitterBuffer **)&jarg1; 
  arg2 = *(JitterBufferPacket **)&jarg2; 
  result = (int)jitter_buffer_get_another(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1get_1pointer_1timestamp(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(JitterBuffer **)&jarg1; 
  result = (int)jitter_buffer_get_pointer_timestamp(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1tick(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(JitterBuffer **)&jarg1; 
  jitter_buffer_tick(arg1);
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1remaining_1span(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  spx_uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(JitterBuffer **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  jitter_buffer_remaining_span(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1ctl(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jintArray jarg3) {
  jint jresult = 0 ;
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  int arg2 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(JitterBuffer **)&jarg1; 
  arg2 = (int)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (void *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  result = (int)jitter_buffer_ctl(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_jitter_1buffer_1update_1delay(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_, jintArray jarg3) {
  jint jresult = 0 ;
  JitterBuffer *arg1 = (JitterBuffer *) 0 ;
  JitterBufferPacket *arg2 = (JitterBufferPacket *) 0 ;
  spx_int32_t *arg3 = (spx_int32_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(JitterBuffer **)&jarg1; 
  arg2 = *(JitterBufferPacket **)&jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (spx_int32_t *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  result = (int)jitter_buffer_update_delay(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1ECHO_1GET_1FRAME_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1ECHO_1SET_1SAMPLING_1RATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(24);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1ECHO_1GET_1SAMPLING_1RATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(25);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1ECHO_1GET_1IMPULSE_1RESPONSE_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(27);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1ECHO_1GET_1IMPULSE_1RESPONSE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(29);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1state_1init(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  SpeexEchoState *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (SpeexEchoState *)speex_echo_state_init(arg1,arg2);
  *(SpeexEchoState **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1state_1init_1mc(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  SpeexEchoState *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (SpeexEchoState *)speex_echo_state_init_mc(arg1,arg2,arg3,arg4);
  *(SpeexEchoState **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1state_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SpeexEchoState *arg1 = (SpeexEchoState *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexEchoState **)&jarg1; 
  speex_echo_state_destroy(arg1);
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1cancellation(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2, jshortArray jarg3, jshortArray jarg4) {
  SpeexEchoState *arg1 = (SpeexEchoState *) 0 ;
  spx_int16_t *arg2 = (spx_int16_t *) 0 ;
  spx_int16_t *arg3 = (spx_int16_t *) 0 ;
  spx_int16_t *arg4 = (spx_int16_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexEchoState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg3 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg3, 0); 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg4 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg4, 0); 
  }
  speex_echo_cancellation(arg1,(short const *)arg2,(short const *)arg3,arg4);
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg2, (jshort *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg3, (jshort *)arg3, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg4, (jshort *)arg4, 0); 
  }
  
  
  
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1cancel(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2, jshortArray jarg3, jshortArray jarg4, jintArray jarg5) {
  SpeexEchoState *arg1 = (SpeexEchoState *) 0 ;
  spx_int16_t *arg2 = (spx_int16_t *) 0 ;
  spx_int16_t *arg3 = (spx_int16_t *) 0 ;
  spx_int16_t *arg4 = (spx_int16_t *) 0 ;
  spx_int32_t *arg5 = (spx_int32_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexEchoState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg3 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg3, 0); 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg4 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg4, 0); 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg5 = (spx_int32_t *) (*jenv)->GetIntArrayElements(jenv, jarg5, 0); 
  }
  speex_echo_cancel(arg1,(short const *)arg2,(short const *)arg3,arg4,arg5);
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg2, (jshort *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg3, (jshort *)arg3, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg4, (jshort *)arg4, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg5, (jint *)arg5, 0); 
  }
  
  
  
  
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1capture(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2, jshortArray jarg3) {
  SpeexEchoState *arg1 = (SpeexEchoState *) 0 ;
  spx_int16_t *arg2 = (spx_int16_t *) 0 ;
  spx_int16_t *arg3 = (spx_int16_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexEchoState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg3 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg3, 0); 
  }
  speex_echo_capture(arg1,(short const *)arg2,arg3);
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg2, (jshort *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg3, (jshort *)arg3, 0); 
  }
  
  
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1playback(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2) {
  SpeexEchoState *arg1 = (SpeexEchoState *) 0 ;
  spx_int16_t *arg2 = (spx_int16_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexEchoState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg2, 0); 
  }
  speex_echo_playback(arg1,(short const *)arg2);
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg2, (jshort *)arg2, 0); 
  }
  
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1state_1reset(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SpeexEchoState *arg1 = (SpeexEchoState *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexEchoState **)&jarg1; 
  speex_echo_state_reset(arg1);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1echo_1ctl(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jintArray jarg3) {
  jint jresult = 0 ;
  SpeexEchoState *arg1 = (SpeexEchoState *) 0 ;
  int arg2 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexEchoState **)&jarg1; 
  arg2 = (int)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (void *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  result = (int)speex_echo_ctl(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1decorrelate_1new(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  SpeexDecorrState *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (SpeexDecorrState *)speex_decorrelate_new(arg1,arg2,arg3);
  *(SpeexDecorrState **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1decorrelate(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2, jshortArray jarg3, jint jarg4) {
  SpeexDecorrState *arg1 = (SpeexDecorrState *) 0 ;
  spx_int16_t *arg2 = (spx_int16_t *) 0 ;
  spx_int16_t *arg3 = (spx_int16_t *) 0 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexDecorrState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg3 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg3, 0); 
  }
  arg4 = (int)jarg4; 
  speex_decorrelate(arg1,(short const *)arg2,arg3,arg4);
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg2, (jshort *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg3, (jshort *)arg3, 0); 
  }
  
  
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1decorrelate_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SpeexDecorrState *arg1 = (SpeexDecorrState *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexDecorrState **)&jarg1; 
  speex_decorrelate_destroy(arg1);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1RESAMPLER_1QUALITY_1MAX_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(10);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1RESAMPLER_1QUALITY_1MIN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1RESAMPLER_1QUALITY_1DEFAULT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1RESAMPLER_1QUALITY_1VOIP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_SPEEX_1RESAMPLER_1QUALITY_1DESKTOP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_RESAMPLER_1ERR_1SUCCESS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)RESAMPLER_ERR_SUCCESS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_RESAMPLER_1ERR_1ALLOC_1FAILED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)RESAMPLER_ERR_ALLOC_FAILED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_RESAMPLER_1ERR_1BAD_1STATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)RESAMPLER_ERR_BAD_STATE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_RESAMPLER_1ERR_1INVALID_1ARG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)RESAMPLER_ERR_INVALID_ARG;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_RESAMPLER_1ERR_1PTR_1OVERLAP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)RESAMPLER_ERR_PTR_OVERLAP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_RESAMPLER_1ERR_1MAX_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)RESAMPLER_ERR_MAX_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4, jintArray jarg5) {
  jlong jresult = 0 ;
  spx_uint32_t arg1 ;
  spx_uint32_t arg2 ;
  spx_uint32_t arg3 ;
  int arg4 ;
  int *arg5 = (int *) 0 ;
  SpeexResamplerState *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (spx_uint32_t)jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  arg3 = (spx_uint32_t)jarg3; 
  arg4 = (int)jarg4; 
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg5 = (int *) (*jenv)->GetIntArrayElements(jenv, jarg5, 0); 
  }
  result = (SpeexResamplerState *)speex_resampler_init(arg1,arg2,arg3,arg4,arg5);
  *(SpeexResamplerState **)&jresult = result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg5, (jint *)arg5, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1init_1frac(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jint jarg6, jintArray jarg7) {
  jlong jresult = 0 ;
  spx_uint32_t arg1 ;
  spx_uint32_t arg2 ;
  spx_uint32_t arg3 ;
  spx_uint32_t arg4 ;
  spx_uint32_t arg5 ;
  int arg6 ;
  int *arg7 = (int *) 0 ;
  SpeexResamplerState *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (spx_uint32_t)jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  arg3 = (spx_uint32_t)jarg3; 
  arg4 = (spx_uint32_t)jarg4; 
  arg5 = (spx_uint32_t)jarg5; 
  arg6 = (int)jarg6; 
  {
    if (!jarg7) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg7) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg7 = (int *) (*jenv)->GetIntArrayElements(jenv, jarg7, 0); 
  }
  result = (SpeexResamplerState *)speex_resampler_init_frac(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  *(SpeexResamplerState **)&jresult = result; 
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg7, (jint *)arg7, 0); 
  }
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  speex_resampler_destroy(arg1);
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1process_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3, jintArray jarg4, jfloatArray jarg5, jintArray jarg6) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t arg2 ;
  float *arg3 = (float *) 0 ;
  spx_uint32_t *arg4 = (spx_uint32_t *) 0 ;
  float *arg5 = (float *) 0 ;
  spx_uint32_t *arg6 = (spx_uint32_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (float *) (*jenv)->GetFloatArrayElements(jenv, jarg3, 0); 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg4, 0); 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg5 = (float *) (*jenv)->GetFloatArrayElements(jenv, jarg5, 0); 
  }
  {
    if (!jarg6) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg6) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg6 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg6, 0); 
  }
  result = (int)speex_resampler_process_float(arg1,arg2,(float const *)arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseFloatArrayElements(jenv, jarg3, (jfloat *)arg3, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg4, (jint *)arg4, 0); 
  }
  {
    (*jenv)->ReleaseFloatArrayElements(jenv, jarg5, (jfloat *)arg5, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg6, (jint *)arg6, 0); 
  }
  
  
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1process_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jshortArray jarg3, jintArray jarg4, jshortArray jarg5, jintArray jarg6) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t arg2 ;
  spx_int16_t *arg3 = (spx_int16_t *) 0 ;
  spx_uint32_t *arg4 = (spx_uint32_t *) 0 ;
  spx_int16_t *arg5 = (spx_int16_t *) 0 ;
  spx_uint32_t *arg6 = (spx_uint32_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg3, 0); 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg4, 0); 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg5 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg5, 0); 
  }
  {
    if (!jarg6) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg6) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg6 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg6, 0); 
  }
  result = (int)speex_resampler_process_int(arg1,arg2,(short const *)arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg3, (jshort *)arg3, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg4, (jint *)arg4, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg5, (jshort *)arg5, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg6, (jint *)arg6, 0); 
  }
  
  
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1process_1interleaved_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloatArray jarg2, jintArray jarg3, jfloatArray jarg4, jintArray jarg5) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  float *arg2 = (float *) 0 ;
  spx_uint32_t *arg3 = (spx_uint32_t *) 0 ;
  float *arg4 = (float *) 0 ;
  spx_uint32_t *arg5 = (spx_uint32_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = (float *) (*jenv)->GetFloatArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (float *) (*jenv)->GetFloatArrayElements(jenv, jarg4, 0); 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg5 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg5, 0); 
  }
  result = (int)speex_resampler_process_interleaved_float(arg1,(float const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseFloatArrayElements(jenv, jarg2, (jfloat *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  {
    (*jenv)->ReleaseFloatArrayElements(jenv, jarg4, (jfloat *)arg4, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg5, (jint *)arg5, 0); 
  }
  
  
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1process_1interleaved_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2, jintArray jarg3, jshortArray jarg4, jintArray jarg5) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_int16_t *arg2 = (spx_int16_t *) 0 ;
  spx_uint32_t *arg3 = (spx_uint32_t *) 0 ;
  spx_int16_t *arg4 = (spx_int16_t *) 0 ;
  spx_uint32_t *arg5 = (spx_uint32_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg4 = (spx_int16_t *) (*jenv)->GetShortArrayElements(jenv, jarg4, 0); 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg5 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg5, 0); 
  }
  result = (int)speex_resampler_process_interleaved_int(arg1,(short const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg2, (jshort *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  {
    (*jenv)->ReleaseShortArrayElements(jenv, jarg4, (jshort *)arg4, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg5, (jint *)arg5, 0); 
  }
  
  
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1set_1rate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t arg2 ;
  spx_uint32_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  arg3 = (spx_uint32_t)jarg3; 
  result = (int)speex_resampler_set_rate(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1get_1rate(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2, jintArray jarg3) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t *arg2 = (spx_uint32_t *) 0 ;
  spx_uint32_t *arg3 = (spx_uint32_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg3 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  speex_resampler_get_rate(arg1,arg2,arg3);
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg2, (jint *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  
  
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1set_1rate_1frac(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t arg2 ;
  spx_uint32_t arg3 ;
  spx_uint32_t arg4 ;
  spx_uint32_t arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  arg3 = (spx_uint32_t)jarg3; 
  arg4 = (spx_uint32_t)jarg4; 
  arg5 = (spx_uint32_t)jarg5; 
  result = (int)speex_resampler_set_rate_frac(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1get_1ratio(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2, jintArray jarg3) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t *arg2 = (spx_uint32_t *) 0 ;
  spx_uint32_t *arg3 = (spx_uint32_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg2, 0); 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg3 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg3, 0); 
  }
  speex_resampler_get_ratio(arg1,arg2,arg3);
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg2, (jint *)arg2, 0); 
  }
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg3, (jint *)arg3, 0); 
  }
  
  
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1set_1quality(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)speex_resampler_set_quality(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1get_1quality(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (int *) (*jenv)->GetIntArrayElements(jenv, jarg2, 0); 
  }
  speex_resampler_get_quality(arg1,arg2);
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg2, (jint *)arg2, 0); 
  }
  
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1set_1input_1stride(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  speex_resampler_set_input_stride(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1get_1input_1stride(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t *arg2 = (spx_uint32_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg2, 0); 
  }
  speex_resampler_get_input_stride(arg1,arg2);
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg2, (jint *)arg2, 0); 
  }
  
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1set_1output_1stride(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  arg2 = (spx_uint32_t)jarg2; 
  speex_resampler_set_output_stride(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1get_1output_1stride(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2) {
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  spx_uint32_t *arg2 = (spx_uint32_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = (spx_uint32_t *) (*jenv)->GetIntArrayElements(jenv, jarg2, 0); 
  }
  speex_resampler_get_output_stride(arg1,arg2);
  {
    (*jenv)->ReleaseIntArrayElements(jenv, jarg2, (jint *)arg2, 0); 
  }
  
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1get_1input_1latency(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  result = (int)speex_resampler_get_input_latency(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1get_1output_1latency(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  result = (int)speex_resampler_get_output_latency(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1skip_1zeros(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  result = (int)speex_resampler_skip_zeros(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1reset_1mem(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  SpeexResamplerState *arg1 = (SpeexResamplerState *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SpeexResamplerState **)&jarg1; 
  result = (int)speex_resampler_reset_mem(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jbyteArray JNICALL Java_com_morlunk_jumble_audio_speex_SpeexJNI_speex_1resampler_1strerror(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jbyteArray jresult = 0 ;
  int arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (char *)speex_resampler_strerror(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


#ifdef __cplusplus
}
#endif

