/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.celt;

public interface CELTConstants {
  public final static int CELT_OK = CELTJNI.CELT_OK_get();
  public final static int CELT_BAD_ARG = CELTJNI.CELT_BAD_ARG_get();
  public final static int CELT_INVALID_MODE = CELTJNI.CELT_INVALID_MODE_get();
  public final static int CELT_INTERNAL_ERROR = CELTJNI.CELT_INTERNAL_ERROR_get();
  public final static int CELT_CORRUPTED_DATA = CELTJNI.CELT_CORRUPTED_DATA_get();
  public final static int CELT_UNIMPLEMENTED = CELTJNI.CELT_UNIMPLEMENTED_get();
  public final static int CELT_INVALID_STATE = CELTJNI.CELT_INVALID_STATE_get();
  public final static int CELT_ALLOC_FAIL = CELTJNI.CELT_ALLOC_FAIL_get();
  public final static int CELT_GET_MODE_REQUEST = CELTJNI.CELT_GET_MODE_REQUEST_get();
  public final static int CELT_SET_COMPLEXITY_REQUEST = CELTJNI.CELT_SET_COMPLEXITY_REQUEST_get();
  public final static int CELT_SET_PREDICTION_REQUEST = CELTJNI.CELT_SET_PREDICTION_REQUEST_get();
  public final static int CELT_SET_VBR_RATE_REQUEST = CELTJNI.CELT_SET_VBR_RATE_REQUEST_get();
  public final static int CELT_RESET_STATE_REQUEST = CELTJNI.CELT_RESET_STATE_REQUEST_get();
  public final static int CELT_RESET_STATE = CELTJNI.CELT_RESET_STATE_get();
  public final static int CELT_GET_FRAME_SIZE = CELTJNI.CELT_GET_FRAME_SIZE_get();
  public final static int CELT_GET_LOOKAHEAD = CELTJNI.CELT_GET_LOOKAHEAD_get();
  public final static int CELT_GET_SAMPLE_RATE = CELTJNI.CELT_GET_SAMPLE_RATE_get();
  public final static int CELT_GET_BITSTREAM_VERSION = CELTJNI.CELT_GET_BITSTREAM_VERSION_get();
}
