/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morlunk.jumble.audio.celt;

public interface CELTConstants {
  public final static int CELT_OK = CELTJNI.CELT_OK_get();
  public final static int CELT_BAD_ARG = CELTJNI.CELT_BAD_ARG_get();
  public final static int CELT_BUFFER_TOO_SMALL = CELTJNI.CELT_BUFFER_TOO_SMALL_get();
  public final static int CELT_INTERNAL_ERROR = CELTJNI.CELT_INTERNAL_ERROR_get();
  public final static int CELT_CORRUPTED_DATA = CELTJNI.CELT_CORRUPTED_DATA_get();
  public final static int CELT_UNIMPLEMENTED = CELTJNI.CELT_UNIMPLEMENTED_get();
  public final static int CELT_INVALID_STATE = CELTJNI.CELT_INVALID_STATE_get();
  public final static int CELT_ALLOC_FAIL = CELTJNI.CELT_ALLOC_FAIL_get();
  public final static int CELT_SET_COMPLEXITY_REQUEST = CELTJNI.CELT_SET_COMPLEXITY_REQUEST_get();
  public final static int CELT_SET_PREDICTION_REQUEST = CELTJNI.CELT_SET_PREDICTION_REQUEST_get();
  public final static int CELT_SET_BITRATE_REQUEST = CELTJNI.CELT_SET_BITRATE_REQUEST_get();
  public final static int CELT_RESET_STATE_REQUEST = CELTJNI.CELT_RESET_STATE_REQUEST_get();
  public final static int CELT_RESET_STATE = CELTJNI.CELT_RESET_STATE_get();
  public final static int CELT_SET_VBR_CONSTRAINT_REQUEST = CELTJNI.CELT_SET_VBR_CONSTRAINT_REQUEST_get();
  public final static int CELT_SET_VBR_REQUEST = CELTJNI.CELT_SET_VBR_REQUEST_get();
  public final static int CELT_SET_INPUT_CLIPPING_REQUEST = CELTJNI.CELT_SET_INPUT_CLIPPING_REQUEST_get();
  public final static int CELT_GET_AND_CLEAR_ERROR_REQUEST = CELTJNI.CELT_GET_AND_CLEAR_ERROR_REQUEST_get();
  public final static int CELT_GET_LOOKAHEAD_REQUEST = CELTJNI.CELT_GET_LOOKAHEAD_REQUEST_get();
  public final static int CELT_SET_CHANNELS_REQUEST = CELTJNI.CELT_SET_CHANNELS_REQUEST_get();
  public final static int CELT_SET_LOSS_PERC_REQUEST = CELTJNI.CELT_SET_LOSS_PERC_REQUEST_get();
  public final static int CELT_SET_START_BAND_REQUEST = CELTJNI.CELT_SET_START_BAND_REQUEST_get();
  public final static int CELT_SET_END_BAND_REQUEST = CELTJNI.CELT_SET_END_BAND_REQUEST_get();
}
